import { Inter } from 'next/font/google';

import SideNavBar from '../components/sideNavBar';
import { StyledComponentRegistry } from '../lib';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentRegistry>
          <SideNavBar />
          <main>{children}</main>
        </StyledComponentRegistry>
      </body>
    </html>
  );
}
